# Use ctrl+space as main prefix.
set -g prefix C-Space
bind -N "Send prefix" C-Space send-prefix
# Keep original prefix as secondary.
set -g prefix2 C-b

# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -as terminal-features ",*:clipboard"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
# Disable escape time to avoid archaic compound keys injecting `M-...` keybinds because of the duration.
set -s escape-time 0
# TODO: Enable extended-keys when on tmux 3.5+
# set -s extended-keys on
# set -s extended-keys-format csi-u
# set -ag terminal-features "xterm-alacritty:extkeys"

# Vi copy-mode

set -g mode-keys vi
# Vim-style visual+yank.
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
# Improve mouse-based drag-and-drop selection.
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel
# Escape copy-mode vi-style.
bind -T copy-mode-vi Escape send -X cancel

# Status bar

# TODO  Better title string.
set -g set-titles on
set -g set-titles-string '#h:#W'

set -g status-position top
set -g status-interval 5
# TODO  Better status left/right templates.
# set -g status-left "#[fg=black,bg=blue,bold] #S #[bg=default] "
# set -g status-right "#[fg=blue]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#h "
set -g status-right ""
# set -g status-left-length 30
# set -g status-right-length 50
set -g window-status-separator ""
set -g window-status-format "#[fg=brightblack] #I:#W "
set -g window-status-current-format "#[fg=blue,bold] #I:#W "

# Theme

set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=blue"
set -g message-style "bg=default,fg=blue"
set -g message-command-style "bg=default,fg=blue"
set -g mode-style "bg=blue,fg=black"
set -g status-style "bg=default,fg=default"
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_path}'
set -gw clock-mode-colour blue

# Window control

bind -N "Create new window" -n M-w new-window -c "#{pane_current_path}" #

bind -N "Switch to window 1" -n M-1 select-window -t 1
bind -N "Switch to window 2" -n M-2 select-window -t 2
bind -N "Switch to window 3" -n M-3 select-window -t 3
bind -N "Switch to window 4" -n M-4 select-window -t 4
bind -N "Switch to window 5" -n M-5 select-window -t 5
bind -N "Switch to window 6" -n M-6 select-window -t 6
bind -N "Switch to window 7" -n M-7 select-window -t 7
bind -N "Switch to window 8" -n M-8 select-window -t 8
bind -N "Switch to window 9" -n M-9 select-window -t 9

# Pane control

# Killing a pane without discreet panes will fall back to killing the nearest context, e.g. the window.
bind -N "Close current pane" -n M-q kill-pane

bind -N "Split window Horizontally" -n M-p split-window -h -c "#{pane_current_path}"
bind -N "Split window Vertically" -n M-l split-window -v -c "#{pane_current_path}"

bind -N "Expand pane Vertically" -n C-M-Up resize-pane -U 10
bind -N "Shrink pane Vertically" -n C-M-Down resize-pane -D 10
bind -N "Shrink pane Horizontally" -n C-M-Left resize-pane -L 10
bind -N "Expand pane Horizontally" -n C-M-Right resize-pane -R 10

# Pane navigation does not wrap.
bind -N "Move pane up" -n M-up if -F '#{pane_at_top}' '' 'select-pane -U'
bind -N "Move pane down" -n M-down if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind -N "Move pane left" -n M-left if -F '#{pane_at_left}' '' 'select-pane -L'
bind -N "Move pane right" -n M-right if -F '#{pane_at_right}' '' 'select-pane -R'

