-- Show which key has been pressed and which subsequent commands and motions are available.
return {
    'folke/which-key.nvim',
    event = 'VimEnter',
    opts = {
        delay = 0,
        icons = {
            mappings = vim.g.use_nerd_font,
            keys = vim.g.use_nerd_font and {} or {
                Up = '<Up> ',
                Down = '<Down> ',
                Left = '<Left> ',
                Right = '<Right> ',
                C = '<C-…> ',
                M = '<M-…> ',
                D = '<D-…> ',
                S = '<S-…> ',
                CR = '<CR> ',
                Esc = '<Esc> ',
                ScrollWheelDown = '<ScrollWheelDown> ',
                ScrollWheelUp = '<ScrollWheelUp> ',
                NL = '<NL> ',
                BS = '<BS> ',
                Space = '<Space> ',
                Tab = '<Tab> ',
                F1 = '<F1>',
                F2 = '<F2>',
                F3 = '<F3>',
                F4 = '<F4>',
                F5 = '<F5>',
                F6 = '<F6>',
                F7 = '<F7>',
                F8 = '<F8>',
                F9 = '<F9>',
                F10 = '<F10>',
                F11 = '<F11>',
                F12 = '<F12>',
            },
        },
        spec = {
            { '<leader>c', group = 'Code', mode = { 'n', 'x' } },
            { '<leader>g', group = 'Git', mode = { 'n', 'v' } },
            { '<leader>o', group = 'Open' },
            { '<leader>s', group = 'Search' },
            { '<leader>t', group = 'Toggle' },
        },
    },
}
